//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public string TraineeID { get; set; }
        public string TopicID { get; set; }
        public string ClassID { get; set; }
        public string Score1 { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
