//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPTSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public string TrainerID { get; set; }
        public string TrainerAccount { get; set; }
        public string TrainerPassword { get; set; }
        public string TrainerName { get; set; }
        public string TrainerPhoneNumber { get; set; }
        public string TrainerEmail { get; set; }
        public string TrainerExpertise { get; set; }
        public string TrainerWorkplace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
